spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
#    url: ${SPRING_DATASOURCE_URL}
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
#    username: ${SPRING_DATASOURCE_USERNAME}
    username: ${POSTGRES_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
     # data-locations: classpath:demo-data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30
springdoc:
  override-with-generic-response: false
