spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
#    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
#    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
     # data-locations: classpath:demo-data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: MTExMTExMTExMTExMWRzY3ZmZHZkIGtuYmdrbWxrZGtsY3h6azsnO2MnO2N6OycNCnonDQpjDQp4dnNhY2RzdmYNCiBnIG5oO2wgbCw7Y3Y=
    access: 3600000
    refresh: 25920000000
springdoc:
  override-with-generic-response: false
